config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "static_pages#home"
  resources :trips do
    resources :locations
  end

  resources :locations do
    resources :addresses
  end
  resources :trips do
    resources :reviews 
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_one :address, dependent: :destroy


def self.get_spot(searchString)
  @client = GooglePlaces::Client.new('AIzaSyDW72uDnvL5HWkdz47zH60dh8QhbBar_dA')
  @client.spots_by_query(searchString)
end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips
  def full_name
    "#{self.first_name}  #{self.last_name}"

  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
before_action :set_location
before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = @location.addresses
  end

  def show
  end

  def new
    @address = @location.create_address
  end

  def create
    # @user = current_user
    # @shop = Shop.create(params[:shop])
    # @user.shop = @shop

      @address = Address.create(params[:location])
      if @address.save
      redirect_to location_address_path(@location.trip_id, @location)
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to trip_location_path(@location.trip_id,@location)
    else
      render :edit
    end
  end

  def destroy
    @address.destroy
    redirect_to location_path
  end

  private

  def address_params
    params.require(:address).permit(:street, :city, :state, :lat, :long)
  end

  def set_address
    @address = Address.find(params[:id])
  end

  def set_location
    @location = Location.find(params[:location_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

before_action :authenticate_user!, except: [:home]

protected
   def configure_permitted_parameters
     update_attrs = [:first_name, :last_name, :password, :password_confirmation, :current_password, ]
    devise_parameter_sanitizer.permit :account_update, keys: update_attrs

     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
   end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  # before_action :set_spot
  before_action :set_location, only: [:show, :edit, :update, :destroy, :set_spot]
  
  def index
    @locations = @trip.locations.all
  end

  def show
    @spot = Location.get_spot(@location.name)

  end

  def new
    @location = @trip.locations.new
    render :new
  end

  def create
    @location = @trip.locations.new(location_params)

    if @location.save
      redirect_to trip_location_path(@trip.id, @location.id)
    else
      render :new
    end

  end

  def edit
    render :edit
  end

  def update
    if @location.update(location_params)
      redirect_to trip_location_path(@trip, @location)
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trips_path
  end

  private

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name, :fee, :image)
    end

    def set_address
      @address = Address.find(params[:location_id])
    end


    def set_spot()
    end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_trip
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  def index
    @reviews = @trip.reviews.all

  end

  def show
  end

  def new
    @review = Review.new

  end

  def create
    @review = @trip.reviews.new(review_params)
    if @review.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def edit
    render :edit

  end

  def update
    if @review.update(review_params)
     redirect_to trip_path(@trip)
   else
     render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to trip_path(@trip)

  end

  private
  def set_trip
    @trip = Trip.find(params[:trip_id])
  end
  def set_review
    @review = Review.find(params[:id])
  end
  def review_params
    params.require(:review).permit(:body, :author)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
     @trips = current_user.trips.all
  end


  def show
  end

  def new
    @trip = Trip.new
    render :new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    
    if @trip.save
    redirect_to trips_path(@trip.id)
    else 
      render :new
    end
  end

  def edit
   
  end

  def update
    if @trip.update(trip_params)
      redirect_to @trip
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private
    def set_trip
      @trip = current_user.trips.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:name, :start_date, :end_date)
    end

    
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model:[@location, @address], local:true, class:"ui form") do |f|%>
  <div class='field'>
    <%= f.label :street %>
    <%= f.text_field :street, autofocus:true, required:false, placeholder:"123456 Yucca Needle Ave"%>
  </div>

  <div class='field'>
    <%= f.label :city %>
    <%= f.text_field :city, required:false, placeholder:"Saguaro City"%>
  </div>

  <div class='field'>
    <%= f.label :state %>
    <%= f.text_field :state, required:false, placeholder:"Ut"%>
  </div>

  <div class='field'>
    <%= f.label :lat %>
    <%= f.text_field :lat, required:false, placeholder:"38.611128"%>
  </div>

    <div class='field'>
      <%= f.label :long %>
      <%= f.text_field :long, required:false, placeholder:"-109.608368"%>
    </div>
  <%= f.submit "Save" %>
<%end%>

app/views/addresses/edit.html.erb
<h1>Addresses#edit</h1>
<%= render partial:"form" %>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1>Addresses#new</h1>
<%= render partial: "form" %>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class = "ui menu">
  <%= link_to 'Adventurist', root_path, class: "item" %>
  <% if current_user%>
  <%= link_to "Trips", trips_path, class: "item"  %>
  <%= link_to "Add Trip", new_trip_path, class: "item"  %>
  <% end %>
  <div class = "right menu">
    <% if current_user%>
    <%= link_to "Change user info", edit_user_registration_path, class: "item" %>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'ui red button' %>
      <% else %>
       <%= link_to 'Register', new_user_registration_path, class: "item" %>
       <%= link_to 'Log in', new_user_session_path, class: "item" %>
    <% end%>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class = "ui container main_container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<h1><%= @location.id ? "Edit Location" : "Create Location" %></h1>
<hr />
<%= form_with(model: [@trip, @location], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image, class: "input" %>
  </div>
  <div class="field">
  <%= f.label :fees %>
  <%= f.text_field :fees, class: "input" %> 
  </div>
  <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/locations/edit.html.erb
<%= render "form"%>

app/views/locations/index.html.erb
<h1>Location Location Location</h1>
<%= link_to "Where to Next?", new_trip_location_path(@trip), class: "ui button" %>
<ul>
  <% @locations.each do |location| %>
    <li><%= link_to location.name, trip_location_path(@trip, location) %></li>
  <% end %>
</ul>

app/views/locations/new.html.erb
<%= render "form"%>

app/views/locations/show.html.erb
<div style = "display:flex;">




<div class="ui card">
  <div class="content">
    <div class="center aligned header">
<h1><%= @location.name %></h1>
</div>
    <div class="center aligned description">
    <%= @location.address ? @location.address.street : "" %>
    <%= @location.address ? @location.address.city : "" %>
    <%= @location.address ? @location.address.state : "" %><br/><br/>
      <p>Lat<% @location.address ? @location.address.lat : "" %></p><p>long
      <% @location.address ? @location.address.long : "" %></p>
      <img src = "<%= @location.image %>"/>
<p>That'll be: <%= @location.fees %></p>
    </div>
  </div>
  <div class="extra content">
    <div class="center aligned author">
      <img class="ui avatar image" src="https://semantic-ui.com/images/avatar/small/jenny.jpg"> <%=@trip.name%>
    </div>
  </div>
</div>







<div class= "buttons_div">

<%#= link_to "Back to Locations", trip_locations_path(@trip), class: "ui button blue" %>
<%= link_to "Add Address", new_location_address_path(@location), class: "ui button green" %>
<%= link_to "Edit Address", edit_location_address_path(@location,@location.address.id), class: "ui button yellow" %>
<%= link_to "Locations", trip_path(@trip), class: "ui button" %>
<%= link_to "Back to All Locations", trips_path(@trip), class: "ui button green"%>

<%= link_to "Edit Location", edit_trip_location_path([@trip, @location]), class: "ui button inverted blue" %>
<%= link_to "Delete Location", trip_location_path(@trip, @location), class: "ui button inverted red", method: :delete %>
</div>
<div class = "spot">
<%= @spot %>
</div>

app/views/reviews/_form.html.erb
<h1><%= @review.id ? "Edit review" : "Create review" %></h1>
<hr />
<%= form_with(model: [@trip, @review ], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, required: true, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, class: "input" %>
  </div>

  <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/reviews/_review.html.erb
<p>Author: <%= review.author %></p>
<p> <%= review.body %></p>

<%= link_to 'Edit review', edit_trip_review_path(@trip, review), class: 'ui button' %>

<%= link_to 'Delete review', trip_review_path(@trip, review), method: :delete, class: 'ui button' %>
<hr />

app/views/reviews/edit.html.erb
<%= render "form"%>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<%= render "form"%>

app/views/reviews/show.html.erb
<%# <%= redirect_to trip_path(@trip) %> %>

app/views/static_pages/home.html.erb
<div class= "home_background">

<h1>Welcome to your next favorite trip planner</h1>
<h3> plan your next trip: <%= link_to 'view all trips', trips_path, class: "ui button" %>
</h3>
</div>

app/views/trips/_form.html.erb
<h1><%= @trip.id ? "Edit Trip" : "Create Trip" %></h1>
<hr />
<%= form_with(model: @trip, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name,required: true, autofocus: true, class: "input" %>
  </div>
 <div class="field">
   <%= f.label :start_date %>
   <%= f.text_field :start_date, class: "input" %>
 </div>
 <div class="field">
   <%= f.label :end_date %>
   <%= f.text_field :end_date, class: "input" %>
 </div>
 <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/trips/edit.html.erb
<%= render "form"%>

app/views/trips/index.html.erb
<h1 id="name" style="text-align: center"> Welcome <%= current_user.full_name %></h1>

<h1>View your trips</h1>
<hr />
<div class="ui grid">
  <% @trips.each do |trip| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
   
   
      <div class="ui card">
       
        <div class="content">
          <%= link_to "#{trip.name}", trip, class: "ui button trip_name"%>
        </div>
         <div class = "description">
        <%trip.locations.each do |l| %>
            <h4 style = "text-align: center;"><%=l.name%></h4>
        <%end%>
      </div>
        <div class="extra content">
          <div class="two_buttons">
              <%= link_to(edit_trip_path(trip)) do %>
            <div class="ui  green button inverted">
            Edit
            </div>
            <%end%>
              <%= link_to(trip_path(trip) , method: :delete, data: {confirm: "are you sure?"}) do%>
            <div class="ui red button inverted">
              Delete
            </div>
            <%end%>
            
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<h4>feeling adventurous? click here to get 5 random trips</h4>

<h4>view all trips</h4>

app/views/trips/new.html.erb
<%= render "form"%>

app/views/trips/show.html.erb
<h1><%= @trip.name %></h1>
<div class ="button_div">

<%= link_to "Edit Trip", edit_trip_path(@trip), class: "ui button" %>
<br />
<%= link_to "Delete Trip", trip_path(@trip.id), class: "ui button", method: :delete %>
</div>
<hr />

<h1>Location Location Location</h1>
<%= link_to "Where to Next?", new_trip_location_path(@trip), class: "ui button" %>
<div class = "ui grid">
  <% @trip.locations.each do |location| %>
<%#= link_to location.name, trip_location_path(@trip, location) %>

<div class="sixteen wide mobile eight wide tablet four wide computer column">
  <div class= "ui card">
    <div class = "content">
      <%= link_to "#{location.name}", trip_location_path(@trip, location), class: "ui button location_name" %>
      </div>
      <div class = "description">
          <%= location.address.street%>
        </div>
        <div class= "extra content">

        </div>




      </div>
    </div>
  <% end %>

</div>

<h1>reviews</h1>
<%= link_to 'add review', new_trip_review_path(@trip), class: "ui button" %>
<hr />

<% @trip.reviews.each do |review| %>

<%= render 'reviews/review', {review: review } %>


<% end %>